# top level stuff you probably don't need to touch
highlighter: pygments
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: https://allmanbrent.github.io/
baseurl: https://allmanbrent.github.io/
title: Brent Allman
author: Brent Allman
description: Personal blog and resume
avatar: profile.png
email: allmanbrent@gmail.com
github: brentallman # username
#twitter: username
linkedin: brent-allman-1b7414ab
#stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
#disqus: username
#google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
